# Generated by Django 3.0.7 on 2020-07-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=50)),
                ('lName', models.CharField(max_length=50)),
                ('biography', models.TextField()),
                ('publisher', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('book_ISBN', models.CharField(max_length=20, unique=True)),
                ('price', models.FloatField()),
                ('genre', models.CharField(max_length=20)),
                ('yearPublished', models.IntegerField()),
                ('copiesSold', models.IntegerField(default=0)),
                ('publisher', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.Author')),
            ],
        ),
    ]
