# Generated by Django 3.0.7 on 2020-07-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200711_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authorID',
            new_name='author',
        ),
    ]
